### ISSUE TITLE
Make architecture selection clearer and more user friendly

### ISSUE THREAD

**Issue by JoeHCQ1** [defenseunicorns/uds-cli#1022]
### Is your feature request related to a problem? Please describe

As a mac user, who is normally working on UDS applications and bundles which only support amd64, most UDS CLI tasks are non-starters and difficult to make work for a few reasons:

1. If no architecture is specified, it assumes my processor's architecture. This is a bad assumption - the destination cluster's architecture has no relationship to my dev machine architecture. I'm not running a cluster on this machine either, it's in the cloud (I can't run most of my stuff on this machine). This assumption has also made debugging harder as I get no intel on when exactly UDS stops targeting the architecture I requested and starts targeting my processor's architecture. -- this might be wrong if the references to `UDS_ARCH` in tasks are it referring to the user arch, but then that's immensely unclear. Say `USER_ARCH` or `UDS_USER_ARCH`.

2. The UDS tasks which a user might investigate reference a `UDS_ARCH` variable. If they set that in their environment, it won't work. While externally visible, that's apparently only an internal value, we're seeing part of the task runner's internals in the YAML. **This needs to be fixed.** [Users have](https://defense-unicorns.slack.com/archives/C06QJAUHWFN/p1731596862613049), and will continue to try to fix problems by following the breadcrumbs exposed to them in the ecosystem. It's the job of the product creators to make sure those crumbs lead them the right way. That [the docs](https://github.com/defenseunicorns/uds-cli/blob/main/docs/reference/CLI/uds-runner.md#architecture-environment-variable) mention this isn't enough - people don't read the docs, the docs haven't always encourage repeat visits - and the far more believable problem when having difficulties here is that the tool is broken, not you should check the docs to see if the variable you saw exposed is actually settable. It's not an intuitive question to ask. Of course a variable referenced in shell form `${UDS_ARCH}` is a shell variable - why wouldn't it be?

3. If you try to set the architecture with the `-a`/`--architecture` flag in the form `uds run dev -a amd64` the `-a` flag will have no effect. If I understand correctly, this is because the `-a` ended up being sent to Maru, not the UDS CLI. This is an internal implementation detail that should not be making a difference to the user. My entry point is `uds` and I gave a command to it. There's nothing in my context that implied the existence of this "maru" and so there's no reason I'd be able to deduce this as the cause of my error. It's unintuitive.

### Describe the solution you'd like

1. Never assume the architecture. Assumptions are a fail-slow behavior, if I've not been clear, I want to know that now and clarify. Perhaps architecture could be explicitly pulled from the environment _in a UDS task_ - maybe that's what's happening, if so, make that clear. `UDS_USER_ARCH` as a default tells me a lot more than `UDS_ARCH`.
2. Make it clear how I set architecture via a variable or at least remove breadcrumbs that are misdirecting. Doing `1` above may be sufficient.
3. Catch the `-a`/`--architecture` flag if a user passes it to UDS, forget about the invisible break between the UDS CLI and the Maru task runner inside the command. This isn't intuitive to users. And it's a silent error. As a user, I'm talking to UDS. Maru isn't part of my conversation. UDS should hear me when I talk to it.
4. If architectures will be assumed, only assume on tasks which are applicable only to k3d development cycles (example, assume it for `uds run default` and pass the user architecture downstream, to configure the others).

### Additional context

Defense Unicorns slack threads with platform engineers losing time and productivity to this confusion:
- https://defense-unicorns.slack.com/archives/C06QJAUHWFN/p1731596862613049
- https://defense-unicorns.slack.com/archives/C06QJAUHWFN/p1726781591203709

**Comment by zachariahmiller** [comment]
100% agree that this belongs in this repo vs maru. on the fence about bug or feature, but i think you summed it up reasonably. 

For what its worth, i agree the ux here is confusing. Its especially frustrating when combined with the `only.cluster.architecture: amd64` being set on some zarf packages. 


As for the specific case you had listed, for reference in case anyone else has a similar issue the way to work past using system arch by default and overriding it optionally in tasks is as follows:

```yaml
# tasks.yaml

variables:
  - name: ARCH
    default: ${UDS_ARCH}

tasks:
  - name: example
    description: "Example task"
    inputs:
      architecture:
        description: The architecture of the package to create
        default: ${ARCH}
    actions:
      - cmd: echo ${{ .inputs.architecture }}
```
```bash
$ uds run example
arm64  
$ uds run example --set ARCH="amd64"
amd64
```

notably, this would also work with the with key like so:

```yaml
includes:
  - create: https://raw.githubusercontent.com/defenseunicorns/uds-common/v1.2.2/tasks/create.yaml
variables:
  - name: ARCH
    default: ${UDS_ARCH}
tasks:
  - name: create-dev-package
    description: Create the Valkey package
    inputs:
      architecture:
        description: The architecture of the package to create
        default: ${ARCH}
    actions:
      - task: create:package
        with:
          options: "--skip-sbom"
          architecture: "${{ .inputs.architecture }}"
```
