### ISSUE TITLE
Bundle creation fails with local zarf init package

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-cli#1039]
### Environment

Device and OS: macOS
App version: 0.19.2
Kubernetes distro being used: N/A

### Steps to reproduce

1. Pull zarf's init package locally (`zarf tools download-init`).
2. Attempt to include this in your bundle, for example something like this:
```yaml
packages:
kind: UDSBundle
metadata:
  name: init-bundle
  version: "0.1.0"

packages:
  - name: zarf-init
    path: ./
    ref: 0.44.0
```

### Expected result

Bundle creates successfully.

### Actual Result

Bundle fails to create due to expecting a different path. Note:
```
     ERROR:  failed to create bundle: open <some-path-here>/zarf-package-zarf-init-arm64-0.44.0.tar.zst: no such file or directory
```

Whereas zarf init packages end up locally without the `zarf-package` prefix.

### Severity/Priority

Low, this is unlikely to be something that people are doing, but could be hit with custom init packages if not desiring to publish them in a registry. Easy workaround to move/rename the file.

### Additional Context

CLI just makes the assumption that local packages have `zarf-package-` as the prefix, possibly should also just check for `zarf-init` (I think the file is guaranteed to be named this for init packages, but worth confirming).
