### ISSUE TITLE
Support remote task files

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#151]
Investigate the usage of remote task files, decide if this is something we want to support

Context:
For instance, I may define a set of tasks that are universally use across a suite of repositories (stand up a cluster, tear down a cluster, etc) and instead of copy-pasting those tasks reop-to-repo, prefer to keep things DRY. It seems to me the older schema may have afforded that evolution better this update.

There were some early discussions surrounding DRY with whatever task running we do. Could I create a handful of tasks that are useful to many repos, stick them in one location, and use them for both CI and local development? That would be very powerful

Syntax options:
Option 1
```
#local task
- name: a-task
  actions:
    - task: local

- name: local
  actions:
    - cmd: echo "hello local"

...

# remote task
actions:
  - task: remote
    ref: https://raw.githubusercontent.com/defenseunicorns/uds-cli/b923cba25730bb487f2e619a0b58d4b9141adecd/src/test/tasks.yaml
```

Option 2
```
include:
   common: ./extra-tasks.yaml
tasks:
  - task: local-task
  - task: common:remote-taske
```
