### ISSUE TITLE
Read config file during `uds remove`

### ISSUE THREAD

**Issue by mikevanhemert** [defenseunicorns/uds-cli#161]
### Is your feature request related to a problem? Please describe

`uds remove` does not read the config file (`uds-config.yaml`) and does not set Zarf variables for underlying packages.

### Describe the solution you'd like

- **Given** UDS Bundle with a Zarf package that has an `action.onRemove` defined and there is a valid `uds-config.yaml`
- **When** A Bundle destroyer runs `uds remove`
- **Then** All Zarf variables are set by first reading in the `uds-config.yaml` file

### Additional context

Note: Zarf doesn't currently load Zarf var values for onRemove actions but there is a separate ticket requesting that change

1. Create a directory and load the three files listed below
2. `zarf package create --confirm`
3. `uds create --confirm`
4. `uds deploy uds-bundle*.zst --confirm -l debug`
    * **verify message displayed is `cheers`, verify `templateMap` contents**
5. `uds remove uds-bundle*.zst --confirm -l debug`
    * **note message is not displayed and `templateMap` has not been loaded**

### `zarf.yaml`
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/zarf/main/zarf.schema.json
kind: ZarfPackageConfig
metadata:
  name: test
  version: 0.1.0

variables:
  - name: MESSAGE
    default: a-hoy-hoy

components:
  - name: test
    required: true
    actions:
      onDeploy:
        after:
          - cmd: echo ${ZARF_VAR_MESSAGE}
      onRemove:
        after:
          - cmd: echo ${ZARF_VAR_MESSAGE}
```

### `uds-bundle.yaml`
```yaml
kind: UDSBundle
metadata:
  name: bundle
  version: 0.1.0

zarf-packages:
  - name: test
    path: ./
    ref: 0.1.0
```

### `uds-config.yaml`
```yaml
bundle:
  deploy:
    zarf-packages:
      test:
        set:
          MESSAGE: cheers
  remove:
    zarf-packages:
      test:
        set:
          MESSAGE: cheers
```
