### ISSUE TITLE
uds run cannot rerun tasks in the same execution

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-cli#193]
### Is your feature request related to a problem? Please describe

In uds version 0.1.0, when i try to call a task multiple times, i get an error:
```
  DEBUG   2023-11-12T19:21:02-05:00  -  task loop detected
  ERROR:  Failed to run action: task loop detected
```

Minimal reproduction of the issue:
```
tasks:
  - name: error
    actions:
      - task: rerunnable-task
      - task: rerunnable-task
      - task: rerunnable-task

  - name: rerunnable-task
    actions:
      - cmd: echo "I should be able to be called over and over within reason."
```

In this specific case, I am running something where i call a generic zarf-create task that creates a package given WORK_DIR that can be set in the preceding command to make it reusable. I have a task file that have multiple target tasks that can be run separately, or together. This feels like a common use case.

Aside from that scenario, there could also be a task the multiple tasks depend on and as such in order to be able to run the tasks both independently and together, the need to support being called twice. A trivial example of this is something like a "set-env" task that sets some values.

### Describe the solution you'd like

Within reason, tasks should be able to be called multiple times. Obviously there needs to be a codified limit here to allow for error handling, but it should be much greater than 1. Maybe a depth of nested tasks calls that are allowed of a given task being called, possibly like 10.

### Describe alternatives you've considered

writing duplicate tasks for everything, but this is not desirable.
