### ISSUE TITLE
Refactor Bundle Helm Overrides YAML

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#208]
We're currently using the "magic string" syntax. Let's think through alternatives

**Comment by UncleGedd** [comment]
Some examples of what we could do: https://defense-unicorns.slack.com/archives/C06305MN50F/p1699913290641979

**Comment by UncleGedd** [comment]
Going with:
```yaml
overrides:
  podinfo-component:
    unicorn-podinfo:
      values:
        - path: podinfo.ui.color
          value: blue
      valuesFiles:
        - path: values.yaml
      variables:
        - name: UI_COLOR
          path: podinfo.ui.color
          description: "Set the color for podinfo's UI"
          default: "blue"
```
