### ISSUE TITLE
Add Validation to Bundle Overrides

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#209]
### Is your feature request related to a problem? Please describe
For example:
```
    overrides:
      values:
        - path: "podinfo-component/unicorn-podinfo/podinfo.replicaCountadsfadsff"
          value: 2

      variables:
        - name: UI_COLOR
          path: "podinfo-component/unicorn-podinfo/podinfo.ui.color"
          description: "Set the color for podinfo's UI"
          default: "blue"
```
If you misspell or otherwise have an invalid `path`, the deployment will continue without erroring out or letting the user know that there is a mistake.
