### ISSUE TITLE
Allow a cmd to set the default value of a variable

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-cli#217]
### Is your feature request related to a problem? Please describe

There are some variables that change depending on os/hardware that need to referenced in multiple places. The current solution is to have each task that needs this info reference a task that sets those variables. It would be really nice to be able to set default values for those vars in the variables field at the top of the tasks.yaml file

Current:

```yaml
tasks:
  - name: build-zarf
    actions:
      - task: set-os-arch
      - cmd: |
          if [ -f ./zarf ] && [ "$(./zarf version)" = "${ZARF_VERSION}" ] ; then exit 0; fi
          echo "Downloading zarf"
          curl -sL https://github.com/defenseunicorns/zarf/releases/download/${ZARF_VERSION}/zarf_${ZARF_VERSION}_${PLATFORM}_${ARCH} -o ./zarf
          chmod +x ./zarf
        dir: build
  - name: set-os-arch
    actions:
      - cmd: |
          ARCH=$(uname -m)
          [ "$ARCH" = "x86_64" ] && ARCH="amd64"
          echo $ARCH
        setVariables:
          - name: ARCH
            sensitive: false
      - cmd: uname -s
        setVariables:
          - name: PLATFORM
            sensitive: false
```

Wanted:

```yaml
variables:
  - name: PLATFORM
    defaultCmd:  uname -s
  - name: ARCH
    defaultCmd: |
          ARCH=$(uname -m)
          [ "$ARCH" = "x86_64" ] && ARCH="amd64"
          echo $ARCH
tasks:
  - name: build-zarf
    actions:
      - task: set-os-arch
      - cmd: |
          if [ -f ./zarf ] && [ "$(./zarf version)" = "${ZARF_VERSION}" ] ; then exit 0; fi
          echo "Downloading zarf"
          curl -sL https://github.com/defenseunicorns/zarf/releases/download/${ZARF_VERSION}/zarf_${ZARF_VERSION}_${PLATFORM}_${ARCH} -o ./zarf
          chmod +x ./zarf
        dir: build
```

### Describe the solution you'd like

- **Given** a variable is declared in the variables field
- **When** that variable needs to change depending on environment
- **Then** I can have the variable's value be set via a cmd in the variables field
