### ISSUE TITLE
Refactor uds-config.yaml

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#223]
The current `uds-config.yaml` looks like:
```yaml
bundle:
  deploy:
    log-level: info
    zarf-packages:
      helm:
        set:
          # overrides variables in uds-bundle.yaml
          UI_COLOR: green
          UI_MSG: "Hello Unicorn"
```

Proposing to shorten and clarify the syntax of the config file like so:
```yaml
options:
  log-level: debug
variables:
  helm:
    UI_COLOR: green
    UI_MSG: "Hello Unicorn"
    BUCKETS:
      - name: my-bucket
        region: us-west-2
      - name: my-other-bucket
        region: us-east-1
```
