### ISSUE TITLE
Improve bundle remove logic

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#236]
Given a deployed bundle:
```yaml
kind: UDSBundle
metadata:
  name: example
  description: an example UDS bundle
  version: 0.0.1

zarf-packages:
  - name: nginx
    repository: localhost:888/nginx
    ref: 0.0.1
  - name: podinfo
    repository: localhost:889/podinfo
    ref: 0.0.1
```

If you attempt to `uds remove ... --confirm --packages podinfo` and then `uds remove ... --confirm` the removal will fail because `podinfo` has already been removed.

Let's revamp the remove logic so that if `--packages` isn't provided then UDS CLI can look for Zarf package state secrets to intelligently remove packages
