### ISSUE TITLE
Support passing variables to included tasks

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-cli#256]
### Is your feature request related to a problem? Please describe

I have a UDS task where I would like to run the same task multiple times but with a different variable passed into it. For example I have a task that looks like this:
```yaml
tasks:
  - name: echo
     actions:
       - cmd: "echo $MY_VAR"
```

I want to include this task multiple times in my other tasks but with different values set for `MY_VAR` each time.

### Describe the solution you'd like

I would like to be able to import the task and set a `vars` key to define my variables for that individual "included run". As an example:
```yaml
includes:
  - echo: ./echo.yaml
 
tasks:
  - name: foobar
    actions:
      - task: echo:echo
        vars:
          - MY_VAR: "foo"
      - task: echo:echo
        vars:
          - MY_VAR: "bar"
```

### Describe alternatives you've considered

I could call `uds run` from within a uds task, which will work but is a bit clunky.

I could also use multiple actions back to back to `setVariables` then run an included action.

### Additional context

Due to the above workarounds this is not a blocking issue, just an optimization that would be nice to have.
