### ISSUE TITLE
Variables in includes "reset" the variable (tasks)

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-cli#260]
### Environment

Device and OS: macOS
App version: 0.4.1
Kubernetes distro being used: N/A

### Steps to reproduce

Create two task files:
```yaml
# deploy.yaml
variables:
  - name: SOME_VAR

tasks:
  - name: foobar
    actions:
      - cmd: echo "${SOME_VAR}"
```

```yaml
# tasks.yaml
variables:
  - name: SOME_VAR

includes:
  - deploy: deploy.yaml

tasks:
  - name: foobar
    actions:
      - task: deploy:foobar
```

Run the below commands:
```console
uds run foobar --set SOME_VAR="test"
uds run -f deploy.yaml foobar --set SOME_VAR="test"
```

### Expected result

Both tasks should output "test".

### Actual Result

Only the second command outputs "test". The first outputs an empty string. By removing the `variables` declaration from `deploy.yaml` the example works as expected. 

It seems like defining a variable in a task that gets included effectively "resets" the variable value.

### Severity/Priority

Low - workarounds available.

**Comment by TristanHoladay** [comment]
Seeing something similar and probably related:

### Attempt 1
tasks.yaml
```yaml
includes:
  - create: ./tasks/create.yaml
  - publish: ./tasks/publish.yaml

tasks:
  - name: create-pkg-flavor
    actions:
      - task: create:cert-manager-pkg-flavor
        # variables: 
        #   - name: FLAVOR
        #     default: "upstream"

  - name: publish-pkg-flavor
    actions:
      - tasks: publish:cert-manager-pkg-flavor
  ```
  create.yaml
  ```yaml
  variables:
  - name: FLAVOR
    default: "upstream"

tasks:
  - name: cert-manager-pkg-flavor
    description: "Create pkg flavor of Cert-Manager"
    actions:
      - cmd: mkdir ${FLAVOR}
      - cmd: zarf package create . --flavor=${FLAVOR} -o ${FLAVOR}/ --confirm
  ```
  `uds run task create-pkg-flavor --set FLAVOR=registry1` --> value does not get passed down to create.yaml
  *If i remove the default value from create.yaml then the task fails because nothing is set for that variable
  
  ### Attempt 2

  tasks.yaml
```yaml
includes:
  - create: ./tasks/create.yaml
  - publish: ./tasks/publish.yaml

tasks:
  - name: create-pkg-flavor
    actions:
      - task: create:cert-manager-pkg-flavor
        variables: 
           - name: FLAVOR
             default: "upstream"

  - name: publish-pkg-flavor
    actions:
      - tasks: publish:cert-manager-pkg-flavor
  ```
  
  create.yaml
  ```yaml
tasks:
  - name: cert-manager-pkg-flavor
    description: "Create pkg flavor of Cert-Manager"
    actions:
      - cmd: mkdir ${FLAVOR}
      - cmd: zarf package create . --flavor=${FLAVOR} -o ${FLAVOR}/ --confirm
  ```
  `uds run task create-pkg-flavor --set FLAVOR=registry1` --> works
  `uds run task create-pkg-flavor --set FLAVOR=upstream` --> works
  `uds run task create-pkg-flavor` --> counting on the default value does NOT work
