### ISSUE TITLE
Don't process all includes if not needed to run a task

### ISSUE THREAD

**Issue by decleaver** [defenseunicorns/uds-cli#280]
If you are running a task that references an include, uds-cli processes all of the includes, even if it doesn't need all of them. Issue was found with the following test :

```
	t.Run("test includes paths", func(t *testing.T) {
		t.Parallel()

		// NOTE: Even though the foobar task doesn't use remote include, since it does reference an "include", all the "includes" get processed,
		// which means we must set "GIT_REVISION" for the remote include
		// get current git revision
		gitRev, err := e2e.GetGitRevision()
		if err != nil {
			return
		}
		setVar := fmt.Sprintf("GIT_REVISION=%s", gitRev)

		stdOut, stdErr, err := e2e.RunTasksWithFile("run", "foobar", "--set", setVar)
		require.NoError(t, err, stdOut, stdErr)
		require.Contains(t, stdErr, "echo foo")
		require.Contains(t, stdErr, "echo bar")
	})
```

Given the following tasks.yaml content:

```
includes:
  - local: ./tasks-to-import.yaml
  - foo: ./more-tasks/foo.yaml
  - remote: https://raw.githubusercontent.com/defenseunicorns/uds-cli/${GIT_REVISION}/src/test/tasks/remote-import-tasks.yaml

- name: foobar
    actions:
      - task: foo:foobar
```

We had to set the GIT_REVISION var because "remote" needs it, even though it does not get used by the foobar task.
