### ISSUE TITLE
Allow parallelization of package deployments in bundles

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-cli#30]
Basically the title, some deployments could be a lot faster if you could deploy multiple packages in a bundle simultaneously. Not sure of solution but would def be nice.

**Comment by zachariahmiller** [comment]
@corang I'm assuming this isnt a priority for the uds-cli at the moment, but i was going through the backlog and was curious on your thoughts of how to accomplish this. 

Specifically, what do you envision the bundle syntax that would facilitate defining which packages in a bundle can execute concurrently looking like?

**Comment by corang** [comment]
Probably something similar to github actions concurrency groups https://docs.github.com/en/actions/using-jobs/using-concurrency
Either of these syntaxes(syntax is going to be very wrong)

define group in each pacakge:
would be executed as follows
1. serial-package-1
2. serial-package-2
3. parallel-package-1-group-1 & parallel-package-2-group-1 & parallel-package-3-group-1
4. parallel-package-1-group-2 & parallel-package-2-group-2 & parallel-package-3-group-2

can be confusing if like below parallel packages aren't grouped which syntactically they don't technically need to be
```yaml
packages:
- name: serial-package-1

- name: serial-package-2

- name: parallel-package-1-group-1
  concGroup: group-1

- name: parallel-package-2-group-1
  concGroup: group-1

- name: parallel-package-1-group-2
  concGroup: group-2

- name: parallel-package-2-group-2
  concGroup: group-2

- name: parallel-package-3-group-2
  concGroup: group-2

- name: parallel-package-3-group-1
  concGroup: group-1
```

allow grouping of multiple package under a single entry in `packages`:

More of a radical change, same execution order as above but avoids the problem of confusing ordering in the bundle yaml vs the actual execution order

```yaml
packages:
- name: serial-package-1

- name: serial-package-2

- name: group-1
  concPackages:
  - name: parallel-package-1-group-1
  - name: parallel-package-2-group-1
  - name: parallel-package-3-group-1

- name: group-2
  concPackages:
  - name: parallel-package-1-group-2
  - name: parallel-package-2-group-2
  - name: parallel-package-3-group-2
```
