### ISSUE TITLE
`uds remove` uses the wrong zarf package name during removal

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-cli#306]
### Environment

Device and OS: macOS
App version: 0.5.2
Kubernetes distro being used: k3d/k3s 1.27 (issue also observed on rke2 1.27)

### Steps to reproduce

1. Deploy a bundle containing a single package. The package should be named differently from the zarf package, i.e.:
    ```yaml
    packages:
      - name: foo
        repository: ghcr.io/packages/bar # Zarf package named bar
    ```
2. Attempt to remove the bundle with `uds remove`.

### Expected result

Bundle is removed.

### Actual Result

```
      WARNING  Skipping removal of foo. Package not deployed
```

### Severity/Priority

Mid

### Additional Context

It appears that uds-cli is using the name specified in the bundle when trying to do a removal, rather than the underlying zarf package name.
