### ISSUE TITLE
UDS Tasks Variable Defaults Not Passed Down

### ISSUE THREAD

**Issue by TristanHoladay** [defenseunicorns/uds-cli#315]
### Steps to reproduce

1. Create a task.yaml with at least 1 included task
2. Add a variable to the task.yaml and the task file where the tasks is written out.
3. Add a default to the task.yaml variable definition but not to the one in the task.
4. Try running that task without setting the variable via cli

### Expected result
The default set in the task.yaml should carry down to the task.

### Actual Result
The default is not carried down and doesn't work.

### Visual Proof (screenshots, videos, text, etc)
`tasks.yaml`
```yaml
includes:
  - create: ./tasks/create.yaml

variables:
  - name: FLAVOR
    default: "upstream"

tasks:
  - name: create-pkg-flavor
    actions:
      - task: create:cert-manager-pkg-flavor
```

`create.yaml`
```yaml
variables:
  - name: FLAVOR

tasks:
  - name: cert-manager-pkg-flavor
    description: "Create pkg flavor of Cert-Manager"
    actions:
      - cmd: zarf package create . --flavor=${FLAVOR} --confirm
```
![Screenshot from 2024-01-12 12-37-06](https://github.com/defenseunicorns/uds-cli/assets/40547442/7298d5ca-67eb-4804-ab37-43e83a2da323)

There should be a deploy-chart component in that output like this:

![Screenshot from 2024-01-12 12-39-13](https://github.com/defenseunicorns/uds-cli/assets/40547442/a5ab3d56-e135-483c-af7a-c91a47b5f5d2)

### Severity/Priority
Low
