### ISSUE TITLE
Add the ability to define a default task 

### ISSUE THREAD

**Issue by rjferguson21** [defenseunicorns/uds-cli#316]
### Is your feature request related to a problem? Please describe
When picking up a new project with a new `tasks.yaml` it is sometimes difficult to know which task is the most common entry point.  It would be nice to be able to signal to consumers of the tasks.yaml which task is generally used.  

It could either be defined by some convention based name (task named `default`), similar to how go-task does it, or an boolean flag on the task.

Option A:
```
tasks:
  - name: default
    actions:
      - cmd: echo "default"
```
Option B:   
```
tasks:
  - name: my-most-used-task
    default: true
    actions:
      - cmd: echo "my-most-used-task"
```   

### Describe the solution you'd like

- **Given** a project that contains a `tasks.yaml` with a default task defined
- **When** `uds run` is run without a task argument
- **Then**  The default task is run

### Describe alternatives you've considered
To avoid scenarios where folks accidentally run the default task by running `uds run`, another option would be requiring users type `uds run default`  which would act as an alias to the default task.

Also improving usage of the task `description` would probably go a long way in improving initial comprehension of new-to-them tasks.yaml.
