### ISSUE TITLE
A user should never be able to select which components get deployed from a package in a bundle when `optional-components` is declared

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-cli#32]
Error log:
```
                                                                                                      
  📦 LOGGING COMPONENT                                                                                
                                                                                                      

     ERROR:  Failed to deploy bundle: unable to deploy all components in this Zarf Package: unable to deploy
             component logging: unable to deploy component logging: unable to push images to the registry: open
             /tmp/zarf-2357824383/images/blobs/sha256/0abe676a9b183901b27c89d50397611e820be40583fe02ef94e148fe33956f00:
             no such file or directory
```
Bundle spec:
```
zarf-packages:
  # Zarf init
  - name: init
    repository: ghcr.io/defenseunicorns/packages/init
    ref: v0.29.1
    optional-components:
      - git-server
```
Deploy without confirm and select logging as a component you want.

Bundles are meant to be declaritive, by allowing user choice of components in packages during deploy time you lose that declaritiveness. I think a user should never be allowed to select components but I'll settle for not allowing when optional-components is specified.
