### ISSUE TITLE
Possible Bug with UDS Tasks Sub Includes

### ISSUE THREAD

**Issue by TristanHoladay** [defenseunicorns/uds-cli#323]
### Steps to reproduce
1. Create a task.yaml with at least 1 task
2. create a file for that 1 task which includes another task from another file
3. try running the top level task

### Expected result
Task should execute all sub tasks

### Actual Result
UDS says it can't find the included sub task

### Visual Proof (screenshots, videos, text, etc)

`task.yaml`
```yaml
includes:
  # - lint: ./tasks/lint.yaml
  - create: ./tasks/create.yaml
  - setup: ./tasks/setup.yaml
  - deploy: ./tasks/deploy.yaml
  - test: ./tasks/test.yaml

tasks:
  - name: setup-cluster
    actions:
      - task: setup:k3d-test-cluster

  - name: create-single-package
    actions:
      - task: create:single-package

  - name: create-standard-package
    actions:
      - task: create:standard-package

  - name: deploy-single-package
    actions:
      - task: deploy:single-package

  - name: test-single-package
    actions:
      - task: test:single-package

  - name: test-uds-core
    actions:
      - task: test:uds-core
```

`test.yaml`
```yaml
includes:
  - lint: ./tasks/lint.yaml
  - create: ./tasks/create.yaml
  - setup: ./tasks/setup.yaml
  - deploy: ./tasks/deploy.yaml

tasks:
  - name: single-package
    description: "Build and test a single package, must set UDS_PKG environment variable"
    actions:
      - task: create:single-package
      - task: setup:k3d-test-cluster
      - task: deploy:single-package

      - description: "Validate the package"
        cmd: uds run -f src/${UDS_PKG}/tasks.yaml validate --no-progress

  - name: uds-core
    description: "Build and test UDS Core"
    actions:
      - task: lint:format-pepr
      - task: create:standard-package
      - task: create:istio-package
      - task: create:k3d-standard-bundle
      - task: deploy:k3d-standard-bundle

      - description: "Validated all packages"
        # loop through each src/* package and run the validate.yaml task
        cmd: |
          set -e        
          for package in src/*; do
            uds run -f ${package}/tasks.yaml validate --no-progress
          done
```

```tristan@tristan-NUC13ANHi7:~/repos/uds/uds-core$ uds run test-uds-core

 NOTE  Saving log file to /tmp/uds-2024-01-16-13-16-06-2710112168.log
     ERROR:  Failed to run action: task name lint:format-pepr not found
```

### Severity/Priority
low
