### ISSUE TITLE
Handle or document recommendation for "zarf flavors"

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-cli#332]
### Is your feature request related to a problem? Please describe

Zarf has added support for `flavors` in packages which allows the creation of multiple versions of a package with a single `zarf.yaml` and then creation using the `--flavor` parameter. The published packages are then published to tags matching `<version>-<flavor>`.

Currently UDS does not have a documented/programmatic approach to handling zarf flavors. If I wanted to create equivalent "flavored" bundles consuming flavored zarf packages I would have to duplicate my bundle (if pulling from OCI) and ensure I publish them to two different paths/tags.

### Describe the solution you'd like

I'm not sure if UDS _should_ handle flavors automatically, but it would be good to consider options to make using zarf flavors in a bundle easier. Even just documenting a good approach/standard would be helpful.

It's worth considering that a UDS bundle could have multiple different zarf package flavors in it, so this isn't necessarily a 1:1 relationship. For this reason I don't think it necessarily makes sense to fully incorporate flavors into the UDS bundle schema, but perhaps it would be useful to expose a flag during create or publish to tack on additional pre-release or build metadata to the version listed in the bundle yaml.

### Describe alternatives you've considered

Leave this on the end user to handle, this could lead to inconsistent bundle naming/tagging and confusion on what is being pulled.

**Comment by Racer159** [comment]
One interesting approach to consider could be something like a "flavorGroup" - flavors could be very diverse between packages (since they can represent many different things) but for packages from the same source (i.e. `uds-software-factory`) you could have a lot of repeated values in an override config because of that team / source's standardization of flavors.

Consider the following bundle:

```yaml
kind: UDSBundle
metadata:
  name: swf
  description: A UDS bundle for deploying the UDS Software Factory
  version: 0.1.0

packages:
  - name: swf-deps-aws
    path: ../../
    ref: "0.1.0"
  
  - name: gitlab
    repository: ghcr.io/defenseunicorns/packages/uds/gitlab
    ref: 16.8.1-uds.2
    flavorGroup: image-source
 
  - name: gitlab-runner
    repository: ghcr.io/defenseunicorns/packages/uds/gitlab-runner
    ref: 16.8.0-uds.0
    flavorGroup: image-source

  - name: sonarqube
    repository: ghcr.io/defenseunicorns/packages/uds/sonarqube
    ref: 8.0.3-uds.4
    flavorGroup: image-source

  - name: mattermost
    repository: ghcr.io/defenseunicorns/packages/uds/mattermost
    ref: 9.4.1-uds.2
    flavorGroup: image-source
    
  - name: llama-cpp-python
    repository: ghcr.io/defenseunicorns/packages/leapfrogai/llama-cpp-python
    ref: "0.2.0"
    flavorGroup: ai-type
```

These groups could then be specified on the CLI or in a config like:

```bash
uds create . --flavorGroup image-source=registry1 --flavorGroup ai-type=gpu
```
