### ISSUE TITLE
unable to pass boolean annotation values to istio helm charts

### ISSUE THREAD

**Issue by brianrexrode** [defenseunicorns/uds-cli#362]
### Environment

Device and OS: EC2 instance:Amazon Linux 2
App version: v0.6.2
Kubernetes distro being used: EKS 1.27
Other:

### Steps to reproduce

1. overrides for uds-core
```
    overrides:
      istio-admin-gateway:
        gateway:
          values:
            - path: service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-cross-zone-load-balancing-enabled
              value: "true"
            - path: service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-internal
              value: "true"
      istio-tenant-gateway:
        gateway:
          values:
            - path: service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-cross-zone-load-balancing-enabled
              value: "true"
            - path: service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-internal
              value: "true"
      istio-passthrough-gateway:
        gateway:
          values:
            - path: service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-cross-zone-load-balancing-enabled
              value: "true"
            - path: service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-internal
              value: "true"
```

### Expected result
The istio-ingress service gets annotations:
```
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```
and the AWS associated ELB gets provisioned

### Actual Result
uds-core deployment fails
```
WARNING  Unable to complete helm chart install/upgrade, waiting 10 seconds and trying again: unable
          to build kubernetes objects from release manifest: unable to decode "": json: cannot
          unmarshal bool into Go struct field ObjectMeta.metadata.annotations of type string
```

### Additional Context

Add any other context or screenshots about the technical debt here.

**Comment by decleaver** [comment]
setting it to the following worked:
```
      istio-admin-gateway:
        gateway:
          values:
            - path: service.annotations
              value:
                service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
                service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      istio-tenant-gateway:
        gateway:
          values:
            - path: service.annotations
              value:
                service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
                service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      istio-passthrough-gateway:
        gateway:
          values:
            - path: service.annotations
              value: 
                service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
                service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```
The way it was set before the helm code was being "smart" and converting the string "true" into a boolean value which was causing the issues.
