### ISSUE TITLE
Including the same zarf package twice errors on local creation

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-cli#372]
### Environment

Device and OS: MBP
App version: 0.6.2
Kubernetes distro being used: N/A

### Steps to reproduce

1. Attempt to create a bundle similar to the below:
    ```yaml
    kind: UDSBundle
    metadata:
      name: test
      version: 0.0.1
    
    packages:
      - name: dev-postgres1
        repository: ghcr.io/defenseunicorns/packages/uds/dev-postgres
        ref: 0.0.1
      
      - name: dev-postgres2
        repository: ghcr.io/defenseunicorns/packages/uds/dev-postgres
        ref: 0.0.1
    ```

Note the duplication of the same package here.

### Expected result

Bundle creates successfully.

### Actual Result

```console
? Create this bundle? Yes
  ✔  Bundle Validated                                                                                                                                                                                                           

                                                                                                      
  🐕 Fetching Packages                                                                                
                                                                                                      

  ⠸  Fetching dev-postgres1 package layer metadata (package 1 of 2) (1s)                                                                                                                                                            
  ✔  Successfully pulled bundle: dev-postgres1 (66.94 KBs)                                                                                                                                                                          
  ⠸  Fetching dev-postgres2 package layer metadata (package 2 of 2) (1s)                                                                                                                                                         
     ERROR:  Failed to create bundle: sha256:7072b95fb91449996deae9735176ca7288e14bac69bd9b74cd5c1af3777a2257:
             application/vnd.oci.image.manifest.v1+json: already exists
```

### Visual Proof (screenshots, videos, text, etc)

Included above.

### Severity/Priority

Low for my scenario, a second bundle could be created.
