### ISSUE TITLE
Rethink UDS_ENV approach in Runner

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#380]
Example:
```yaml
  - name: env-from-file
    actions:
      # create a .env and load it into env var UDS_ENV
      - cmd: |
          echo "FOO=bar" >> .env
          cat .env >> $UDS_ENV
          rm .env
      - cmd: echo $FOO
```

And the corresponding code in `runner.go`
```go
	// load the contents of the env file into the Action, then an action load other env vars by referencing UDS_ENV
	// in an action and appending more env vars to $UDS_ENV (see task env-from-file in src/test/tasks/tasks.yaml)
	// todo: rethink this approach, don't make users write bash to load env vars or a .env
	action.Env = append(action.Env, strings.Split(string(currentEnvFileContents), "\n")...)
	action.Env = append(action.Env, "UDS_ENV="+r.EnvFilePath)
```

Having users write bash to append env vars to a file in an effort to load their env vars into runner tasks is not a great UX. Rethink and refactor this approach so users don't have to write the "clever" bash
