### ISSUE TITLE
False task loop detected when referencing multiple tasks from the same include in an actions

### ISSUE THREAD

**Issue by decleaver** [defenseunicorns/uds-cli#391]
### Environment
uds v0.8.0

### Steps to reproduce
With a task file similar to:
```
includes:
  - create: ./tasks/create.yaml
  - setup: ./tasks/setup.yaml
  - helper: ./tasks/helper.yaml
  - deploy: ./tasks/deploy.yaml

tasks:
  - name: deploy-all
    actions:
      - task: setup:download-uds-configs
      - task: create:create-bundle
      - task: helper:deploy-additional
      - task: helper:udpate-uds-config
      - task: deploy:deploy-uds-bundle
  ```

### Expected result
- runs task `deploy-all` successfully

### Actual Result
- fails because of the two tasks in the actions that reference the same include `helper`
