### ISSUE TITLE
Tasks and includes cannot share a common base name

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-cli#410]
if there is an include and a task that share a name the included tasks cannot be found:
```
includes:
- taskone: some.yaml

tasks:
- name: taskone
  actions:
    - task: taskone:someincludedtask
```
`uds run taskone` fails with `Failed to run action: task name taskone:someincludedtask not found`

real example here https://github.com/defenseunicorns/uds-package-artifactory/blob/main/tasks.yaml#L34-L36

**Comment by UncleGedd** [comment]
From your real-world example, will changing `cleanup` to `cleanup-all` fix the issue?

```yaml

  - name: cleanup-all
    actions:
      - task: cleanup:destroy
```
