### ISSUE TITLE
task runner - `dir` does not work with variables

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-cli#411]
### Environment

Device and OS: m2 mac
App version: uds 0.8.1
Kubernetes distro being used: N/A
Other:

### Steps to reproduce

1. create this task file:

```yaml
variables:
  - name: DIR
    default: "bundle"

tasks:
  - name: default
    actions:
      - task: no-inputs-no-vars-with-dir
      - task: no-inputs-yes-vars-with-dir


  # hardcoded dir working
  - name: no-inputs-no-vars-with-dir
    actions:
      - cmd: pwd
        dir: bundle

  - name: no-inputs-yes-vars-with-dir
    actions:
      - cmd: pwd
        dir: $DIR
```
2. `mkdir bundle`
3. `uds run`

### Expected result
both tasks succeed and output path

### Actual Result
1st suceeds, 2nd fails

### Visual Proof (screenshots, videos, text, etc)
![image](https://github.com/defenseunicorns/uds-cli/assets/71521611/5dd1b33b-0c5c-4f1e-a8cf-c7754df1a1c4)

### Severity/Priority
pretty important for task re-usability

### Additional Context

I'm trying to work on adding the inputs functionality to the reusable tasks so they are able to be used in the SWF integration repo, which does not confirm to the exact structure of the uds single package repos 

Just FYI i tried `$DIR` as `$DIR`, `${DIR}`, same as previous two but quoted as well as exporting from the command line before running.
