### ISSUE TITLE
Import multiple variables from the same package without defining the pkg each time

### ISSUE THREAD

**Issue by brianrexrode** [defenseunicorns/uds-cli#422]
### Is your feature request related to a problem? Please describe

It would be nice to have the ability to import multiple variables from the same package without having to define the package for each variable.

### Describe the solution you'd like
```
packages:
  - name: s3-irsa-iac
    exports:
      - name: LOKI_S3_BUCKET
      - name: LOKI_S3_IRSA_ROLE_ARN
      - name: LOKI_S3_AWS_REGION
      - name: VELERO_S3_BUCKET
      - name: VELERO_S3_IRSA_ROLE_ARN
      - name: VELERO_S3_AWS_REGION
  - name: uds-core
    imports:
      - package: s3-irsa-iac
        name: LOKI_S3_BUCKET
        name: LOKI_S3_IRSA_ROLE_ARN
        name: LOKI_S3_AWS_REGION
        name: VELERO_S3_BUCKET
        name: VELERO_S3_IRSA_ROLE_ARN
        name: VELERO_S3_AWS_REGION
```

### Describe alternatives you've considered

(optional) A clear and concise description of any alternative solutions or features you've considered.
