### ISSUE TITLE
Support Zarf component deselection in UDS bundles

### ISSUE THREAD

**Issue by rjferguson21** [defenseunicorns/uds-cli#426]
### Is your feature request related to a problem? Please describe

As of this [this PR](https://github.com/defenseunicorns/uds-cli/pull/425), Zarf supports deselection of optional components with `--components=-notthiscomponent`.

We've discussed it being helpful to support a use case where packages can have components that are defaulted to be true but can be disabled.

### Describe the solution you'd like

- **Given** A uds-bundle.yaml
```
kind: UDSBundle
metadata:
  name: uds-stuff
  version: dev

packages:
  - name: podinfo
    path: ./
    ref: "0.0.1"
    # The `-podinfo` disables the podinfo component from the podinfo package
    optionalComponents: 
      - "-podinfo"
```
- **When** The bundle is created and deployed
- **Then** It does not include the deselected `podinfo` component from the `podinfo` package

### Describe alternatives you've considered

The syntax around zarf component deselection is a bit awkward exposed directly in the uds bundle schema via `optionalComponents`.  @zachariahmiller and I discussed it would probably be better to consider updating the schema to remove `optionalComponents` and replace with something like enabled in the `overrides` for the package so you'd end up with this instead.

```
kind: UDSBundle
metadata:
  name: uds-stuff
  version: dev

packages:
  - name: podinfo
    path: ./
    ref: "0.0.1"
    overrides:
      podinfo:
        enabled: false
```
### Additional context
I added a [draft PR to enable the component deselection](https://github.com/defenseunicorns/uds-cli/pull/425) in a quick and dirty way but wanted to discuss that this was the right path forward.
