### ISSUE TITLE
Allow `uds run` of included tasks directly

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-cli#441]
### Is your feature request related to a problem? Please describe

As a task developer I want to be able to run included tasks directly so that I do not have to copy and paste boilerplate that just pulls in the same single task.

### Describe the solution you'd like

- **Given** I have a task imported through an include:

```yaml
variables:
  - name: FLAVOR
    default: "upstream"

tasks:
  - name: package
    description: Create the UDS Zarf Package
    inputs:
      options:
        description: "For setting create time variables and flags"
    actions:
      - cmd: uds zarf package create --confirm --no-progress --architecture=${ZARF_ARCHITECTURE} --flavor ${FLAVOR} ${{ .inputs.options }}
```

```yaml
includes:
  - create: ./tasks/create.yaml
```

- **When** I run `uds run create:package`
- **Then** the sub-task runs

### Describe alternatives you've considered

We could have another syntax but this is already used when referencing another task in yaml

### Additional context

This would reduce the need for repeated dash-separated tasks like this:

```yaml
  - name: deploy-test-bundle
    actions:
      - task: deploy:test-bundle
```
