### ISSUE TITLE
Bundle Creation Failure

### ISSUE THREAD

**Issue by beholdenkey** [defenseunicorns/uds-cli#478]
### Environment

Device and OS: macos
App version: Sonoma 14.3.1
Kubernetes distro being used: N/A
Other:

### Steps to reproduce

1.`create bundles/demo --confirm --no-progress`

```yaml
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/uds-cli/main/uds.schema.json
kind: UDSBundle
metadata:
  name: example
  description: an example UDS bundle
  version: 0.0.1

packages:
  - name: init
    repository: ghcr.io/defenseunicorns/packages/init
    ref: v0.32.4
    optionalComponents:
      - git-server
  - name: podinfo
    repository: ghcr.io/defenseunicorns/uds-cli/podinfo
    ref: 0.0.1
```

### Expected result

Previously, the bundle would create

### Actual Result

```bash
uds create bundles/demo --confirm --no-progress

 NOTE  Saving log file to
       /var/folders/6j/cn07plcd3kbghwc8l1kckddw0000gn/T/uds-2024-02-28-11-09-17-2045085123.log

                                                                                                      
  🎁 BUNDLE DEFINITION                                                                                
                                                                                                      


kind: UDSBundle
metadata:
  name: example
  description: an example UDS bundle
  version: 0.0.1
packages:
- name: init
  repository: ghcr.io/defenseunicorns/packages/init
  ref: v0.32.4
  optionalComponents:
  - git-server
- name: podinfo
  repository: ghcr.io/defenseunicorns/uds-cli/podinfo
  ref: 0.0.1

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  •  Validating bundle
panic: no ':' separator in digest ""

goroutine 1 [running]:
github.com/opencontainers/go-digest.Digest.sepIndex({0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/opencontainers/go-digest@v1.0.0/digest.go:153 +0x90
github.com/opencontainers/go-digest.Digest.Encoded(...)
        /home/runner/go/pkg/mod/github.com/opencontainers/go-digest@v1.0.0/digest.go:137
github.com/defenseunicorns/uds-cli/src/pkg/bundle.(*Bundle).ValidateBundleResources(0x14001800000, 0x14001800008, 0x0?)
        /home/runner/work/uds-cli/uds-cli/src/pkg/bundle/common.go:149 +0x1150
github.com/defenseunicorns/uds-cli/src/pkg/bundle.(*Bundle).Create(0x14001800000)
        /home/runner/work/uds-cli/uds-cli/src/pkg/bundle/create.go:47 +0x108
github.com/defenseunicorns/uds-cli/src/cmd.glob..func9(0x10b9657a0?, {0x1400176e2a0, 0x1, 0x1074ec2fe?})
        /home/runner/work/uds-cli/uds-cli/src/cmd/uds.go:60 +0xec
github.com/spf13/cobra.(*Command).execute(0x10b9657a0, {0x1400176e240, 0x3, 0x3})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x10b9668e0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/defenseunicorns/uds-cli/src/cmd.Execute()
        /home/runner/work/uds-cli/uds-cli/src/cmd/root.go:60 +0x24
main.main()
        /home/runner/work/uds-cli/uds-cli/main.go:19 +0x4c
```

### Visual Proof (screenshots, videos, text, etc)

![Screenshot 2024-02-28 at 11 12 55 AM](https://github.com/defenseunicorns/uds-cli/assets/44618918/e4f4a393-e8e3-4924-8610-5b67ba34274d)

### Additional Context

Add any other context or screenshots about the technical debt here.
