### ISSUE TITLE
GitHub Action to install uds-cli

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/uds-cli#483]
### Is your feature request related to a problem? Please describe

I would like to use `uds-cli` in several workflows across different repositories. The process of installing uds-cli onto the runners so my jobs can use it is a little cumbersome. 

### Describe the solution you'd like

- **Given**: I have a repository
- **When**: I have a workflow that needs to use the `uds-cli`
- **Then**: I have a simple process available to install the cli onto my runner. Ideally, with a step that looks something like:
```yaml
      - name: Install UDS-CLI
        uses: defenseunicorns/setup-uds-cli@{SHA_SUM} # v1.0.0
        with:
          version: 0.9.2
```

### Describe alternatives you've considered

The uds-core repo is currently installing uds-cli onto the runner by first [installing homebrew](https://github.com/defenseunicorns/uds-core/blob/d65acd4e2d37907685ba9083ff98988b4ea1d452/.github/actions/setup/action.yaml#L27) and then running a `brew install uds`. This works, but is a bit clunkier than it needs to be.

### Additional context

There is a [defenseunicorns/setup-zarf](https://github.com/defenseunicorns/setup-zarf) repository that does this same thing for installing the Zarf CLI.
