### ISSUE TITLE
<RUN>_ARCHITECTURE not being honored 

### ISSUE THREAD

**Issue by decleaver** [defenseunicorns/uds-cli#495]
runner architecture env is set to RUN_ARCHITECTURE,  but uds-cli architecture is set to UDS_ARCHITECTURE, need to debug how we can reconcile these two environment variables.

### Environment
```
#tasks.yaml
includes:
  - package: https://raw.githubusercontent.com/defenseunicorns/uds-common-tasks/v0.2.0/tasks/create.yaml

tasks:
  - name: uds-arch-issues
    description: Create the Gitlab runner package
    actions:
      - task: package:test-bundle
```

### Steps to reproduce

1. `RUN_ARCHITECTURE=amd64 ../build/maru-mac-apple run uds-arch-issues`
(where the architecture is different than your OS arch. )

### Expected result
Should create the amd64 version of the bundle

### Actual Result
Creates the arm64 version
