### ISSUE TITLE
UDS command line variables via `--set` are not carried through to Helm

### ISSUE THREAD

**Issue by TheFutonEng** [defenseunicorns/uds-cli#514]
### Is your feature request related to a problem? Please describe

When deploying a UDS package, variables set via `--set` on the command line are not carried through to Helm.  The below command does not carry the values through:

```
 uds deploy --set METALLB_INTERFACE=ens3 --set METALLB_IP_ADDRESS_POOL=192.168.1.250-192.168.1.254 uds-bundle-dco-core-amd64-0.2.1.tar.zst --packages metallb-package
```

Instead, the default values in the `uds-config.yaml` file are what were ultimately set in the cluster:

```
# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/uds-cli/main/uds.schema.json
options:
   log_level: debug
   architecture: amd64
   no_log_file: false
   no_progress: false
   uds_cache: /tmp/uds-cache
   tmp_dir: /tmp/tmp_dir
   insecure: false
   oci_concurrency: 3

shared:
  domain: vp.bigbang.dev # shared across all packages in a bundle

variables:
  metallb-package:
    metallb_interface: primary0
    metallb_ip_address_pool: 192.168.99.250-192.168.99.254
  uds-core:
    admin_tls_cert: <cert here>
    admin_tls_key: <key here>
```

We have a workaround by setting these values as environmental variables prepended with `UDS_`.

```
$ env | grep UDS
UDS_METALLB_INTERFACE=ens3
UDS_METALLB_IP_ADDRESS_POOL=192.168.1.250-192.168.1.254
```

However, relying upon the environment to pass this type of data at deploy time may not always be possible.  The ability to set variables via the CLI would greatly help here.
