### ISSUE TITLE
Support setting package variables  

### ISSUE THREAD

**Issue by rjferguson21** [defenseunicorns/uds-cli#54]
### Currently I believe there are two ways to set variables for zarf packages included in a bundle:

1.  Via the uds-config.yaml 
```
bundle:
  deploy:
    zarf-packages:
      dubbd:
        set:
          FOO: "bar"
```

2. [Via imports/exports](https://github.com/defenseunicorns/uds-cli/blob/main/src/test/packages/02-simple-vars/uds-bundle.yaml#L7-L18)

### I would propose that we support two additional methods of specifying variables
* Accept `--set` argument to bundle deploy to such that you can do something like  `uds bundle deploy --set dubbd.FOO=bar`
* Accept defining variables in the uds-bundle.yaml similar to what is possible with a zarf.yaml:
```
kind: UDSBundle
metadata:
  name: uds-core
  description: uds core
  version: 0.0.1

zarf-packages:
  - name: dubbd
    repository: oci://ghcr.io/defenseunicorns/packages/dubbd
    variables:
      - name: FOO
        default: bar
```
