### ISSUE TITLE
uds create silently succeeds on invalid bundle override definitions

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-cli#558]
### Environment

Device and OS: m2 MBP
App version: 0.10.3
Kubernetes distro being used: N/A
Other:

### Steps to reproduce

1. Make a bundle like this initial part of the gitlab test bundle
```yaml
kind: UDSBundle
metadata:
  name: gitlab-test
  description: A UDS bundle for deploying Gitlab and it's dependencies on a development cluster
  # x-release-please-start-version
  version: 16.10.1-uds.1
  # x-release-please-end

packages:
  - name: dev-minio
    repository: ghcr.io/defenseunicorns/packages/uds/dev-minio
    ref: 0.0.2

  - name: dev-namespace
    path: ../
    ref: 0.1.0

  - name: postgres-operator
    repository: ghcr.io/defenseunicorns/packages/uds/postgres-operator
    ref: 1.10.1-uds.4-upstream
    overrides:
      postgres-operator:
        uds-postgres-config:
          variables:
            - name: POSTGRESQL
              description: "Configure postgres using CRs via the uds-postgres-config chart"
              path: postgresql
```
2. move the postgres-operator overrides and below back two spaces. (like in screenshot). Note the schema can tell its invalid.
![image](https://github.com/defenseunicorns/uds-cli/assets/71521611/e79f2630-92f0-426f-8f83-5c74132cf147)

3. run bundle create

### Expected result

bundle creates invalid syntax

### Actual Result

bundle create succeeds but the override definition is invalid and doesn't work when subsequently deploying the bundle

### Visual Proof (screenshots, videos, text, etc)

I tested multiple times after this issue was brought up to me but the create is embedded inside a longer series of tasks so the output obfuscated. Rest assured it creates. 

### Severity/Priority
🤷 
### Additional Context

Add any other context or screenshots about the technical debt here.
