### ISSUE TITLE
bundle linting

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-cli#577]
### Overview
Given a bundle definition with invalid yaml (such as an extra quote in a package definition), I am able to create the bundle (seemingly without issue), but it fails at deploy time when specifying the invalid package.

### Environment

Device and OS: Ubuntu 22.04
App version: uds `v0.10.3`
Kubernetes distro being used: `uds-k3d:0.6.0` (k8s `1.27.4`)

### Steps to reproduce

1. Make a bad bundle definition with something like:
    ```
    # yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/uds-cli/v0.10.4/uds.schema.json
    kind: UDSBundle
    metadata:
      name: some-bundle
      version: 10.0.0
    
    packages:  
      - name: core
        repository: ghcr.io/defenseunicorns/packages/uds/core
        ref: 0.20.0-registry1
        overrides:
          keycloak:
            keycloak:
              values:
                - path: "devMode""
                  value: "false"
    ```
    > Note the extra quotation after `- path: "devMode"`
2. Build the bundle
3. Deploy the bundle with `--packages core` specified
                  
### Expected result
`uds create` should fail due to invalid yaml

### Actual Result
`uds create` fails to parse anything in the package def beyond the extra quote, but silently continues.
In the bundle creation confirmation, the following is shown:
```
     - name: core
       repository: ghcr.io/defenseunicorns/packages/uds/core
       ref: 0.20.0-registry1
       overrides:
         keycloak:
           keycloak:
             values:
             - path: devMode
               value: null
```
Presumably anything past the extra quote in the package definition is effectively truncated.
     
When attempting to deploy the "broken" bundle, the following error is (correctly) thrown:
```  
user@dev:~$ uds deploy --packages core <bundle> --confirm --no-tea
...
ERROR:  Failed to deploy bundle: invalid zarf packages specified by --packages
```
