### ISSUE TITLE
Check bundle arch against cluster arch

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#656]
### Steps to reproduce

Assume my cluster arch is amd64 and I'm deploying from my arm64 Mac. Consider the following:
```yaml
# uds-bundle.yaml
kind: UDSBundle
metadata:
  name: ghcr-test
  description: testing a bundle of pkgs from ghcr
  version: 0.0.1

packages:
  - name: podinfo
    repository: ghcr.io/defenseunicorns/uds-cli/podinfo
    ref: 0.0.1
  - name: nginx
    repository: ghcr.io/defenseunicorns/uds-cli/nginx
    ref: 0.0.1

---
# tasks.yaml
  tasks:
  - name: default
    actions:
      - cmd: ./uds create . -a amd64 --confirm --no-progress
      - task: deploy

  - name: deploy
    actions:
      - cmd: |
          set -x
          ./uds deploy $(ls -tr uds-bundle*.tar.zst | tail -1) --confirm --no-progress

```

### Expected result

When running `uds run` the bundle creates and deploys successfully

### Actual Result

Bundle create works but on deploy we get this error:
```
          ERROR:  Failed to validate bundle: arch arm64 does not match cluster arch, [amd64]
     ERROR:  Failed to run action: command "set -x; ./uds deploy $(ls -tr uds-bundle*.tar.zst | tail ..." timed
             out after 0 seconds
```

It appears that UDS CLI is checking the user's system arch against the cluster arch

### Additional Context
The workaround is to simply add `-a amd64` to the `uds deploy` command, but this behavior is still bad. During deploy we should check the bundle's arch against the cluster's arch
