### ISSUE TITLE
Consider adding shared values to the bundle definition

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-cli#693]
### Is your feature request related to a problem? Please describe

The bundle config provides a way to set a common deploy-time variable in all packages through the `shared` keyword section.
Occasionally, it would be useful to set a shared value at create-time in the bundle definition

### Describe the solution you'd like

- **Given** a value that should be accessible to all packages
- **When** that value does not need to be configurable by the bundle consumer
- **Then** a bundle maintainer can set a shared value/variable at create-time

Perhaps something like a `sharedVariables` at the top level of the bundle definition which would allow referencing common vars in value overrides later on:
```
kind: UDSBundle
metadata:
  name: example-bundle

sharedVariables:
  SHARING: "CARING"

packages:
  - name: packageA
    overrides:
      packageA:
        chartA:
          values:
            - path: "some.path.in.the.chart"
              value: ${SHARING}
  - name: packageB
    overrides:
      packageB:
        chartB:
          - path: "different.path.same.value"  
            value: ${SHARING}
```

### Describe alternatives you've considered

* Force shared vars to exist in the config
    * This is undesirable because it can lead to unnecessarily exposed options and a more verbose config
* Hardcode the value override in each package
* Use YAML anchors to work around ^the hard coding 

### Additional context

I think this is in line with how we handle overrides in the bundle definition at the package level -- this would just expose the same functionality for shared values/variables to the maintainer
