### ISSUE TITLE
When providing `valuesFiles` values aren't merged correctly

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-cli#695]
### Steps to reproduce

1. Provide a valuesFile to a package in a bundle that has values set in the zarf package
2. deploy zarf package

### Expected result

Values are merged as they would be in a helm deploy

### Actual Result

From what I can tell, if you declare a key in a valuesFile that's declared, say, in a package, the keys aren't merged and are instead just overridden. Example of what I think is happening:

package values
```
config:
  key1: data
  key2:
    key3: data

config2:
  key: data
```

valuesFile
```
config:
  key5: data
```

rendered values:
```
config:
  key5: data

config2:
  key: data
```

### Additional Context

Add any other context or screenshots about the technical debt here.

**Comment by corang** [comment]
real world example:

# Package Values

## common.yaml - 1st
```
global:
  image:
    pullPolicy: IfNotPresent

  ingress:
    configureCertmanager: false

  kas:
    enabled: false

  hosts:
    domain: ###ZARF_VAR_DOMAIN###
    gitlab:
      name: gitlab.###ZARF_VAR_DOMAIN###
    registry:
      name: registry.###ZARF_VAR_DOMAIN###
    pages:
      name: pages.###ZARF_VAR_DOMAIN###
  psql:
    host: ###ZARF_VAR_GITLAB_DB_ENDPOINT###
    port: 5432
    username: ###ZARF_VAR_GITLAB_DB_USERNAME###
    database: ###ZARF_VAR_GITLAB_DB_NAME###
    password:
      useSecret: true
      secret: gitlab-postgres
      key: password

  redis:
    scheme: ###ZARF_VAR_GITLAB_REDIS_SCHEME###
    host: ###ZARF_VAR_GITLAB_REDIS_ENDPOINT###
    port: 6379
    auth:
      enabled: true
      secret: gitlab-redis
      key: password

  minio:
    enabled: false
    credentials:
      {}


  appConfig:
    object_store:
      enabled: true
      proxy_download: true
      connection:
        secret: gitlab-object-store
        key: connection
    lfs:
      bucket: ###ZARF_VAR_BUCKET_PREFIX###gitlab-lfs###ZARF_VAR_BUCKET_SUFFIX###
    artifacts:
      bucket: ###ZARF_VAR_BUCKET_PREFIX###gitlab-artifacts###ZARF_VAR_BUCKET_SUFFIX###
    uploads:
      bucket: ###ZARF_VAR_BUCKET_PREFIX###gitlab-uploads###ZARF_VAR_BUCKET_SUFFIX###
    packages:
      bucket: ###ZARF_VAR_BUCKET_PREFIX###gitlab-packages###ZARF_VAR_BUCKET_SUFFIX###
    externalDiffs:
      bucket: ###ZARF_VAR_BUCKET_PREFIX###gitlab-mr-diffs###ZARF_VAR_BUCKET_SUFFIX###
    terraformState:
      bucket: ###ZARF_VAR_BUCKET_PREFIX###gitlab-terraform-state###ZARF_VAR_BUCKET_SUFFIX###
    ciSecureFiles:
      bucket: ###ZARF_VAR_BUCKET_PREFIX###gitlab-ci-secure-files###ZARF_VAR_BUCKET_SUFFIX###
    dependencyProxy:
      bucket: ###ZARF_VAR_BUCKET_PREFIX###gitlab-dependency-proxy###ZARF_VAR_BUCKET_SUFFIX###
    backups:
      bucket: ###ZARF_VAR_BUCKET_PREFIX###gitlab-backups###ZARF_VAR_BUCKET_SUFFIX###
      tmpBucket: ###ZARF_VAR_BUCKET_PREFIX###gitlab-tmp###ZARF_VAR_BUCKET_SUFFIX###
    ## https://docs.gitlab.com/charts/charts/globals#omniauth
    omniauth:
      enabled: true
      allowSingleSignOn: ['openid_connect']
      blockAutoCreatedUsers: false
      autoLinkUser: true
      autoSignInWithProvider: openid_connect
      externalProviders: []
      syncProfileAttributes: ['email']
      syncProfileFromProvider: []
      providers:
        - secret: gitlab-sso
          key: providers
    initialDefaults:
      signupEnabled: ###ZARF_VAR_GITLAB_SIGNUP_ENABLED###

  registry:
    bucket: ###ZARF_VAR_BUCKET_PREFIX###gitlab-registry###ZARF_VAR_BUCKET_SUFFIX###
    relativeurls: true

  pages:
    enabled: ###ZARF_VAR_GITLAB_PAGES_ENABLED###
    objectStore:
      bucket: ###ZARF_VAR_BUCKET_PREFIX###gitlab-pages###ZARF_VAR_BUCKET_SUFFIX###

  ## https://docs.gitlab.com/charts/charts/globals#service-accounts
  serviceAccount:
    enabled: true
    create: true
    annotations: {}

postgresql:
  install: false
redis:
  install: false
registry:
  storage:
    redirect:
      disable: ###ZARF_VAR_DISABLE_REGISTRY_REDIRECT###
    secret: gitlab-object-store
    key: registry
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

gitlab:
  toolbox:
    backups:
      config:
        secret: gitlab-object-store
        key: backups

  gitlab-exporter:
    enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  migrations:
    resources:
      limits:
        cpu: 500m
        memory: 4G

  sidekiq:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  webservice:
    ingress:
      enabled: false
    metrics:
      enabled: true
      port: 8083
      serviceMonitor:
        enabled: true
    workhorse:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

  gitlab-pages:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  gitaly:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  # override to enable ssh
  gitlab-shell:
    enabled: true
    sshDaemon: gitlab-sshd
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

certmanager:
  install: false

gitlab-runner:
  install: false

prometheus:
  install: false

nginx-ingress: &nginx-ingress
  enabled: false

domain: ###ZARF_VAR_DOMAIN###
```

## registry1.yaml - 2nd
```
gitlab:
  webservice:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-webservice
      tag: 16.11.1
    workhorse:
      image: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-workhorse
      tag: 16.11.1
  sidekiq:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-sidekiq
      tag: 16.11.1
  migrations:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-toolbox
      tag: 16.11.1
  gitaly:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitaly
      tag: 16.11.1
  gitlab-exporter:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-exporter
      tag: 16.11.1
  gitlab-pages:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-pages
      tag: 16.11.1
  gitlab-shell:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-shell
      tag: 16.11.1
  praefect:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitaly
      tag: 16.11.1
  toolbox:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-toolbox
      tag: 16.11.1

global:
  certificates:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/certificates
      tag: 16.11.1
  gitlabBase:
    image:
      repository: registry1.dso.mil/ironbank/redhat/ubi/ubi9
      tag: "9.3"
  kubectl:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/kubectl
      tag: 16.11.1

registry:
  image:
    repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-container-registry
    tag: 16.11.1

shared-secrets:
  selfsign:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/cfssl-self-sign
      tag: 1.6.1

upgradeCheck:
  image:
    repository: registry1.dso.mil/ironbank/redhat/ubi/ubi9
    tag: "9.3"
```

# valuesFile overrides

```
gitlab:
  webservice:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-webservice
      tag: 16.10.2
    resources:
      limits:
        cpu: 1000m
        memory: 5Gi
      requests:
        cpu: 1000m
        memory: 5Gi
    workhorse:
      image: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-workhorse
      tag: 16.10.2
      resources:
        limits:
          cpu: 1000m
          memory: 5Gi
        requests:
          cpu: 1000m
          memory: 5Gi
  sidekiq:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-sidekiq
      tag: 16.10.2
  migrations:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-toolbox
      tag: 16.10.2
  gitaly:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitaly
      tag: 16.10.2
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Exists
    resources:
      limits:
        cpu: 14000m
        memory: 110Gi
      requests:
        cpu: 14000m
        memory: 110Gi
  gitlab-exporter:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-exporter
      tag: 16.10.2
  gitlab-pages:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-pages
      tag: 16.10.2
  gitlab-shell:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-shell
      tag: 16.10.2
  praefect:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitaly
      tag: 16.10.2
  toolbox:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-toolbox
      tag: 16.10.2
    persistence:
      enabled: true
      size: "250Gi"

global:
  appConfig:
    omniauth:
      autoSignInWithProvider: ""
    ciSecureFiles:
      connection:
        key: connection
        secret: gitlab-object-store
      proxy_download: true
  certificates:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/certificates
      tag: 16.10.2
  gitlabBase:
    image:
      repository: registry1.dso.mil/ironbank/redhat/ubi/ubi9
      tag: "9.3"
  kubectl:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/kubectl
      tag: 16.10.2

registry:
  image:
    repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-container-registry
    tag: 16.10.2

shared-secrets:
  selfsign:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/cfssl-self-sign

upgradeCheck:
  image:
    repository: registry1.dso.mil/ironbank/redhat/ubi/ubi9
    tag: "9.3"
```

# Rendered Values

```
domain: stg.sonic.mil
gitlab:
  gitaly:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitaly
      tag: 16.10.2
    persistence:
      size: 200Gi
    resources:
      limits:
        cpu: 14000m
        memory: 110Gi
      requests:
        cpu: 14000m
        memory: 110Gi
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Exists
  gitlab-exporter:
    enabled: true
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-exporter
      tag: 16.10.2
    metrics: null
  gitlab-pages:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-pages
      tag: 16.10.2
  gitlab-shell:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-shell
      tag: 16.10.2
  migrations:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-toolbox
      tag: 16.10.2
    resources:
      limits:
        cpu: 500m
        memory: 4G
  praefect:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitaly
      tag: 16.10.2
  sidekiq:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-sidekiq
      tag: 16.10.2
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws-us-gov:iam::035629041273:role/sonic-stg-gitlab-sidekiq-s3-role
  toolbox:
    backups:
      config:
        key: backups
        secret: gitlab-object-store
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-toolbox
      tag: 16.10.2
    persistence:
      enabled: true
      size: 250Gi
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws-us-gov:iam::035629041273:role/sonic-stg-gitlab-toolbox-s3-role
  webservice:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-webservice
      tag: 16.10.2
    ingress:
      enabled: false
    metrics:
      enabled: true
      port: 8083
      serviceMonitor:
        enabled: true
    resources:
      limits:
        cpu: 1000m
        memory: 5Gi
      requests:
        cpu: 1000m
        memory: 5Gi
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws-us-gov:iam::035629041273:role/sonic-stg-gitlab-webservice-s3-role
    workhorse:
      image: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-workhorse
      resources:
        limits:
          cpu: 1000m
          memory: 5Gi
        requests:
          cpu: 1000m
          memory: 5Gi
      tag: 16.10.2
global:
  appConfig:
    artifacts:
      bucket: sonic-stg-gitlab-artifacts
    backups:
      bucket: sonic-stg-gitlab-backups
      tmpBucket: sonic-stg-gitlab-tmp
    ciSecureFiles:
      bucket: sonic-stg-gitlab-ci-secure-files
      connection:
        key: connection
        secret: gitlab-object-store
      enabled: true
      proxy_download: true
    dependencyProxy:
      bucket: sonic-stg-gitlab-dependency-proxy
      enabled: false
    externalDiffs:
      bucket: sonic-stg-gitlab-external-diffs
      enabled: true
    initialDefaults:
      signupEnabled: true
    lfs:
      bucket: sonic-stg-gitlab-lfs
    object_store:
      connection:
        key: connection
        secret: gitlab-object-store
      enabled: true
      proxy_download: true
    omniauth:
      allowSingleSignOn:
      - openid_connect
      autoLinkUser: true
      autoSignInWithProvider: ""
      blockAutoCreatedUsers: false
      enabled: true
      externalProviders: []
      providers:
      - key: providers
        secret: gitlab-sso-provider-json
      syncProfileAttributes:
      - email
      syncProfileFromProvider: []
    packages:
      bucket: sonic-stg-gitlab-packages
    terraformState:
      bucket: sonic-stg-gitlab-terraform-state
      enabled: true
    uploads:
      bucket: sonic-stg-gitlab-uploads
  certificates:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/certificates
      tag: 16.10.2
  gitlabBase:
    image:
      repository: registry1.dso.mil/ironbank/redhat/ubi/ubi9
      tag: "9.3"
  hosts:
    domain: stg.sonic.mil
    gitlab:
      name: gitlab.stg.sonic.mil
    pages:
      name: pages.stg.sonic.mil
    registry:
      name: registry.stg.sonic.mil
  image:
    pullPolicy: IfNotPresent
  istio:
    enabled: true
    injection: enabled
  kubectl:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/kubectl
      tag: 16.10.2
  minio:
    credentials: {}
    enabled: false
  pages:
    enabled: false
    objectStore:
      bucket: sonic-stg-gitlab-pages
  psql:
    database: gitlabdb
    host: gitlab-db-20240506183639557300000003.c024evwrn970.us-gov-west-1.rds.amazonaws.com
    password:
      key: password
      secret: gitlab-postgres
      useSecret: true
    port: 5432
    username: gitlab
  redis:
    auth:
      enabled: true
      key: password
      secret: gitlab-redis
    host: master.sonic-stg-gitlab.tk3qin.usgw1.cache.amazonaws.com
    port: 6379
    scheme: rediss
  registry:
    bucket: sonic-stg-gitlab-registry
    relativeurls: true
istio:
  enabled: false
  gitlab:
    gateways:
    - istio-tenant-gateway/tenant-gateway
  injection: enabled
  pages:
    customDomains:
      enabled: false
    enabled: true
    gateways:
    - istio-tenant-gatway/tenant-gateway
    hosts:
    - '*.pages.stg.sonic.mil'
    ingressLabels:
      app: tenant-ingressgateway
    port: 8090
  registry:
    gateways:
    - istio-tenant-gateway/tenant-gateway
postgresql:
  install: false
redis:
  install: false
registry:
  image:
    repository: registry1.dso.mil/ironbank/gitlab/gitlab/gitlab-container-registry
    tag: 16.10.2
  metrics:
    serviceMonitor:
      enabled: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws-us-gov:iam::035629041273:role/sonic-stg-gitlab-registry-s3-role
  storage:
    key: registry
    redirect:
      disable: true
    secret: gitlab-object-store
shared-secrets:
  selfsign:
    image:
      repository: registry1.dso.mil/ironbank/gitlab/gitlab/cfssl-self-sign
upgradeCheck:
  image:
    repository: registry1.dso.mil/ironbank/redhat/ubi/ubi9
    tag: "9.3"
```

We also have values being set via the values.variables overrides in the bundle
