### ISSUE TITLE
You can't export variables with the same name across multiple packages

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-cli#70]
Because of how uds-cli stores exported variables having 2 exports with the same variable name doesn't work since the next occurrence of an export overwrites the first one. Simplified version of erroring bundle below

```yaml
kind: UDSBundle
metadata:
  name: software-factory-demo
  description: A UDS bundle for deploying a software factory to k3d for demonstration purposes NOT FOR PRODUCTION
  version: 0.0.2
  architecture: amd64

zarf-packages:
  - name: software-factory-idam-gitlab
    path: build
    ref: 1.0.0
    exports:
      - name: IDAM_ENABLED

  - name: software-factory-idam-sonarqube
    path: build
    ref: 1.0.0
    exports:
      - name: IDAM_ENABLED

  - name: gitlab
    repository: ghcr.io/defenseunicorns/uds-capability/gitlab
    ref: 0.0.9
    imports:
      - name: IDAM_ENABLED
        package: software-factory-idam-gitlab

  - name: sonarqube
    repository: ghcr.io/defenseunicorns/uds-capability/sonarqube
    ref: 0.0.8
    imports:
      - name: IDAM_ENABLED
        package: software-factory-idam-sonarqube
```

Error:

```yaml
Failed to create bundle: error validating bundle vars: import var IDAM_ENABLED does not have a
             matching export
```
