### ISSUE TITLE
docs: Add example on Zarf variable usage

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/uds-cli#72]
SWF Example: https://github.com/defenseunicorns/uds-swf-aws/tree/main/swf-aws-bundle

uds-config.yaml
```yaml
bundle:
  deploy:
    zarf-packages:
      dubbd-aws:
        set:
          domain: bigbang.dev     # These top 4 should be "global"
          key_file: bigbang.dev.key
          cert_file: bigbang.dev.cert
```
