### ISSUE TITLE
bug: `uds bundle create` adding architecture 

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/uds-cli#74]
I want to create bundles for a different architecture than where the command is being execute. (i.e. build and amd64 bundle from an arm64 machine)

With uds-bundle.yaml
```
kind: UDSBundle
metadata:
  name: example
  description: an example UDS bundle
  version: 0.0.1

zarf-packages:
  - name: init 
    repository: ghcr.io/defenseunicorns/packages/init
    ref: v0.29.2-amd64
    optional-components:
      - git-server
```

Running `uds bundle create`
![image](https://github.com/defenseunicorns/uds-cli/assets/46836330/bc43bdfa-496d-4315-bfe0-2fcec9e725c3)
`     ERROR:  Failed to create bundle: ghcr.io/defenseunicorns/packages/rook-ceph:0.0.2-amd64-arm64: not found`
adding the extra `arm64`

UDS-cli Version: v0.0.5-alpha
Running on Apple M2
