### ISSUE TITLE
Add feature for including skeletons in a bundle

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-cli#75]
Slack thread with a bunch of context: https://defense-unicorns.slack.com/archives/C029NJU2S4B/p1696012055101239

Basically if uds products want to have reusable capability dependency packages they need to be specified as skeletons and not as built packages. This is technically currently possible through a bunch of extra steps that I think would make more sense to be internalized into uds-cli. Current workaround implementation:

1. Have a uds-bundle.yaml
2. have that bundle reference 2 local packages
3. each local package (zarf.yaml) references the same skeleton
4. each local package has a different zarf-config.yaml that sets different values for the TMPLs in said skeleton
5. build each package to the directory the bundle expects
6. build bundle

I think a limited implementation of skeletons in bundles could work really well with a syntax like this

```yaml
kind: UDSBundle
metadata:
  name: bundle-of-skeletons

zarf-packages:
  - name: planet-mars
    repository: ghcr.io/defenseunicorns/planet
    ref: 1.0
    skeleton: true
    package-templates:
      - name: PLANET
        value: mars
  - name: planet-neptune
    repository: ghcr.io/defenseunicorns/planet
    ref: 1.0
    skeleton: true
    package-templates:
      - name: PLANET
        value: neptune
```

This obviously does not afford the full flexibility of skeletons (composing and overrides) but gives a very simple path to creating multi-use/reusable package definitions for common needs. A database being a prime example.

You would just run `uds bundle create` as usual and it would handle the building of any skeletons in the bundle for you and then just treat them normally.
