### ISSUE TITLE
actions have whitespace prepended

### ISSUE THREAD

**Issue by Michael-Kruggel** [defenseunicorns/uds-cli#844]
### Steps to reproduce

1. Store indented yaml in a secret
	ex:
	```yaml
	supersecret: |
	  key1:
	    key2: value1
	  key3: value2
	```
2. Retrieve secret via zarf action
	ex:
	```yaml
	actions:
      onDeploy:
        after:
          - cmd: ./zarf tools kubectl get secret secret-name -n secret-namespace -o=jsonpath='{.data.supersecret}' | base64 --decode
	```
### Expected result
Output is this:
```yaml
key1:
  key2: value1          
key3: value2
```
### Actual Result
Output is this:
```yaml
    key1:
  key2: value1                                                                                                                                                                                                                 
key3: value2
```

### Visual Proof (screenshots, videos, text, etc)
![image](https://github.com/user-attachments/assets/6d372dfb-b590-427b-9bc5-382e687cac57)
